window.seedData = {
  "vehicles": [
    {
      "id": "V001",
      "domain": "DEM001",
      "internal": "Q001",
      "model": "Sprinter",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "OLCA",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 2",
      "telepass": "",
      "vtv": "2026-12-18",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "active",
      "odometer": 125604,
      "driver": "Conductor Demo 1",
      "lastReport": "2026-10-01T08:30:00.000Z",
      "x": 12,
      "y": 11
    },
    {
      "id": "V002",
      "domain": "DEM002",
      "internal": "Q002",
      "model": "Sprinter",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "RDA",
      "sector": "9 DE JULIO",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 4",
      "telepass": "",
      "vtv": "2026-12-23",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "alert",
      "odometer": 124974,
      "driver": "Conductor Demo 2",
      "lastReport": "2026-10-02T08:30:00.000Z",
      "x": 36,
      "y": 65
    },
    {
      "id": "V003",
      "domain": "DEM003",
      "internal": "Q003",
      "model": "Partner",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 3",
      "telepass": "SI",
      "vtv": "2026-11-04",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "active",
      "odometer": 114595,
      "driver": "Conductor Demo 3",
      "lastReport": "2026-10-03T08:30:00.000Z",
      "x": 20,
      "y": 53
    },
    {
      "id": "V004",
      "domain": "DEM004",
      "internal": "Q004",
      "model": "Transit",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "EDESUR",
      "sector": "9 DE JULIO",
      "area": "GUARDA",
      "responsible": "Responsable 2",
      "telepass": "NO",
      "vtv": "2026-10-18",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 109800,
      "driver": "",
      "lastReport": "",
      "x": 81,
      "y": 32
    },
    {
      "id": "V005",
      "domain": "DEM005",
      "internal": "Q005",
      "model": "Sprinter",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "CONTRALOR",
      "responsible": "Responsable 4",
      "telepass": "SI",
      "vtv": "2026-11-09",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 110638,
      "driver": "",
      "lastReport": "",
      "x": 28,
      "y": 55
    },
    {
      "id": "V006",
      "domain": "DEM006",
      "internal": "Q006",
      "model": "Transit",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "EDESUR",
      "sector": "9 DE JULIO",
      "area": "TCT",
      "responsible": "Responsable 3",
      "telepass": "",
      "vtv": "2026-12-08",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 136178,
      "driver": "",
      "lastReport": "",
      "x": 56,
      "y": 42
    },
    {
      "id": "V007",
      "domain": "DEM007",
      "internal": "Q007",
      "model": "Amarok",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2023",
      "company": "EDESUR",
      "sector": "PRIMERA JUNTA",
      "area": "CONTRALOR",
      "responsible": "Responsable 1",
      "telepass": "NO",
      "vtv": "2026-11-09",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 70307,
      "driver": "",
      "lastReport": "",
      "x": 80,
      "y": 48
    },
    {
      "id": "V008",
      "domain": "DEM008",
      "internal": "Q008",
      "model": "Amarok",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "Laliance",
      "sector": "9 DE JULIO",
      "area": "GUARDA",
      "responsible": "Responsable 3",
      "telepass": "NO",
      "vtv": "2026-10-08",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 156289,
      "driver": "",
      "lastReport": "",
      "x": 41,
      "y": 82
    },
    {
      "id": "V009",
      "domain": "DEM009",
      "internal": "Q009",
      "model": "Fiorino",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2024",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 8",
      "telepass": "SI",
      "vtv": "2026-10-28",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 55066,
      "driver": "",
      "lastReport": "",
      "x": 88,
      "y": 28
    },
    {
      "id": "V010",
      "domain": "DEM010",
      "internal": "Q010",
      "model": "Fiorino",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "GRTC",
      "responsible": "Responsable 8",
      "telepass": "",
      "vtv": "2026-11-18",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 45029,
      "driver": "",
      "lastReport": "",
      "x": 76,
      "y": 42
    },
    {
      "id": "V011",
      "domain": "DEM011",
      "internal": "Q011",
      "model": "Transit",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "GUARDA",
      "responsible": "Responsable 1",
      "telepass": "",
      "vtv": "2026-12-09",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 61832,
      "driver": "",
      "lastReport": "",
      "x": 72,
      "y": 21
    },
    {
      "id": "V012",
      "domain": "DEM012",
      "internal": "Q012",
      "model": "Partner",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2026",
      "company": "RDA",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 6",
      "telepass": "SI",
      "vtv": "2026-12-25",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 15149,
      "driver": "",
      "lastReport": "",
      "x": 84,
      "y": 49
    },
    {
      "id": "V013",
      "domain": "DEM013",
      "internal": "Q013",
      "model": "Hilux",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "JTC",
      "sector": "12 DE OCT",
      "area": "MEDIDORES",
      "responsible": "Responsable 1",
      "telepass": "SI",
      "vtv": "2026-12-03",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 142399,
      "driver": "",
      "lastReport": "",
      "x": 16,
      "y": 76
    },
    {
      "id": "V014",
      "domain": "DEM014",
      "internal": "Q014",
      "model": "Ranger",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "RDA",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 7",
      "telepass": "SI",
      "vtv": "2026-12-25",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 67730,
      "driver": "",
      "lastReport": "",
      "x": 47,
      "y": 59
    },
    {
      "id": "V015",
      "domain": "DEM015",
      "internal": "Q015",
      "model": "Transit",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2026",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 4",
      "telepass": "SI",
      "vtv": "2026-11-01",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 75323,
      "driver": "",
      "lastReport": "",
      "x": 83,
      "y": 36
    },
    {
      "id": "V016",
      "domain": "DEM016",
      "internal": "Q016",
      "model": "Berlingo",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2018",
      "company": "OLCA",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 6",
      "telepass": "SI",
      "vtv": "2026-12-08",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 142248,
      "driver": "",
      "lastReport": "",
      "x": 35,
      "y": 77
    },
    {
      "id": "V017",
      "domain": "DEM017",
      "internal": "Q017",
      "model": "Ranger",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "CONTRALOR",
      "responsible": "Responsable 7",
      "telepass": "SI",
      "vtv": "2026-10-04",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 127997,
      "driver": "",
      "lastReport": "",
      "x": 53,
      "y": 62
    },
    {
      "id": "V018",
      "domain": "DEM018",
      "internal": "Q018",
      "model": "Fiorino",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2018",
      "company": "EDESUR",
      "sector": "PRIMERA JUNTA",
      "area": "GUARDA",
      "responsible": "Responsable 6",
      "telepass": "SI",
      "vtv": "2026-10-07",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 155584,
      "driver": "",
      "lastReport": "",
      "x": 65,
      "y": 25
    },
    {
      "id": "V019",
      "domain": "DEM019",
      "internal": "Q019",
      "model": "Fiorino",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "CONTRALOR",
      "responsible": "Responsable 2",
      "telepass": "NO",
      "vtv": "2026-12-04",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 156711,
      "driver": "",
      "lastReport": "",
      "x": 9,
      "y": 19
    },
    {
      "id": "V020",
      "domain": "DEM020",
      "internal": "Q020",
      "model": "Amarok",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2024",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "MEDIDORES",
      "responsible": "Responsable 7",
      "telepass": "SI",
      "vtv": "2026-10-13",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 117346,
      "driver": "",
      "lastReport": "",
      "x": 41,
      "y": 66
    },
    {
      "id": "V021",
      "domain": "DEM021",
      "internal": "Q021",
      "model": "Partner",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2026",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 5",
      "telepass": "SI",
      "vtv": "2026-10-19",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 157133,
      "driver": "",
      "lastReport": "",
      "x": 15,
      "y": 48
    },
    {
      "id": "V022",
      "domain": "DEM022",
      "internal": "Q022",
      "model": "Berlingo",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "RDA",
      "sector": "9 DE JULIO",
      "area": "MEDIDORES",
      "responsible": "Responsable 1",
      "telepass": "",
      "vtv": "2026-10-28",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 32962,
      "driver": "",
      "lastReport": "",
      "x": 84,
      "y": 16
    },
    {
      "id": "V023",
      "domain": "DEM023",
      "internal": "Q023",
      "model": "Amarok",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "RDA",
      "sector": "PRIMERA JUNTA",
      "area": "GRTC",
      "responsible": "Responsable 1",
      "telepass": "",
      "vtv": "2026-10-14",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 152044,
      "driver": "",
      "lastReport": "",
      "x": 48,
      "y": 41
    },
    {
      "id": "V024",
      "domain": "DEM024",
      "internal": "Q024",
      "model": "Amarok",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2023",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "GUARDA",
      "responsible": "Responsable 3",
      "telepass": "",
      "vtv": "2026-12-10",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 97883,
      "driver": "",
      "lastReport": "",
      "x": 17,
      "y": 9
    },
    {
      "id": "V025",
      "domain": "DEM025",
      "internal": "Q025",
      "model": "Hilux",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "EDESUR",
      "sector": "9 DE JULIO",
      "area": "MEDIDORES",
      "responsible": "Responsable 5",
      "telepass": "SI",
      "vtv": "2026-11-03",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 111869,
      "driver": "",
      "lastReport": "",
      "x": 44,
      "y": 28
    },
    {
      "id": "V026",
      "domain": "DEM026",
      "internal": "Q026",
      "model": "Hilux",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "RDA",
      "sector": "9 DE JULIO",
      "area": "GRTC",
      "responsible": "Responsable 1",
      "telepass": "",
      "vtv": "2026-12-10",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 42154,
      "driver": "",
      "lastReport": "",
      "x": 25,
      "y": 41
    },
    {
      "id": "V027",
      "domain": "DEM027",
      "internal": "Q027",
      "model": "Sprinter",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2026",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 4",
      "telepass": "",
      "vtv": "2026-11-07",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 84201,
      "driver": "",
      "lastReport": "",
      "x": 72,
      "y": 70
    },
    {
      "id": "V028",
      "domain": "DEM028",
      "internal": "Q028",
      "model": "Partner",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 1",
      "telepass": "NO",
      "vtv": "2026-10-21",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 57357,
      "driver": "",
      "lastReport": "",
      "x": 64,
      "y": 78
    },
    {
      "id": "V029",
      "domain": "DEM029",
      "internal": "Q029",
      "model": "Fiorino",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2018",
      "company": "EDESUR",
      "sector": "PRIMERA JUNTA",
      "area": "TCT",
      "responsible": "Responsable 3",
      "telepass": "",
      "vtv": "2026-10-27",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 159841,
      "driver": "",
      "lastReport": "",
      "x": 26,
      "y": 63
    },
    {
      "id": "V030",
      "domain": "DEM030",
      "internal": "Q030",
      "model": "Ranger",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 4",
      "telepass": "",
      "vtv": "2026-10-22",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 107714,
      "driver": "",
      "lastReport": "",
      "x": 79,
      "y": 60
    },
    {
      "id": "V031",
      "domain": "DEM031",
      "internal": "Q031",
      "model": "Ranger",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 3",
      "telepass": "",
      "vtv": "2026-11-26",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 80055,
      "driver": "",
      "lastReport": "",
      "x": 42,
      "y": 28
    },
    {
      "id": "V032",
      "domain": "DEM032",
      "internal": "Q032",
      "model": "Sprinter",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2018",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 8",
      "telepass": "NO",
      "vtv": "2026-11-27",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 73438,
      "driver": "",
      "lastReport": "",
      "x": 11,
      "y": 92
    },
    {
      "id": "V033",
      "domain": "DEM033",
      "internal": "Q033",
      "model": "Amarok",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2023",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "CONTRALOR",
      "responsible": "Responsable 5",
      "telepass": "NO",
      "vtv": "2026-12-17",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 155565,
      "driver": "",
      "lastReport": "",
      "x": 50,
      "y": 11
    },
    {
      "id": "V034",
      "domain": "DEM034",
      "internal": "Q034",
      "model": "Sprinter",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "RDA",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 2",
      "telepass": "",
      "vtv": "2026-11-12",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 97228,
      "driver": "",
      "lastReport": "",
      "x": 63,
      "y": 85
    },
    {
      "id": "V035",
      "domain": "DEM035",
      "internal": "Q035",
      "model": "Sprinter",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "TCT",
      "responsible": "Responsable 7",
      "telepass": "SI",
      "vtv": "2026-12-26",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 66651,
      "driver": "",
      "lastReport": "",
      "x": 54,
      "y": 63
    },
    {
      "id": "V036",
      "domain": "DEM036",
      "internal": "Q036",
      "model": "Sprinter",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2023",
      "company": "RDA",
      "sector": "12 DE OCT",
      "area": "TCT",
      "responsible": "Responsable 2",
      "telepass": "",
      "vtv": "2026-11-17",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 122057,
      "driver": "",
      "lastReport": "",
      "x": 49,
      "y": 59
    },
    {
      "id": "V037",
      "domain": "DEM037",
      "internal": "Q037",
      "model": "Partner",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "TCT",
      "responsible": "Responsable 7",
      "telepass": "",
      "vtv": "2026-12-06",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 93892,
      "driver": "",
      "lastReport": "",
      "x": 59,
      "y": 78
    },
    {
      "id": "V038",
      "domain": "DEM038",
      "internal": "Q038",
      "model": "Berlingo",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "CONTRALOR",
      "responsible": "Responsable 6",
      "telepass": "NO",
      "vtv": "2026-11-15",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 71020,
      "driver": "",
      "lastReport": "",
      "x": 73,
      "y": 68
    },
    {
      "id": "V039",
      "domain": "DEM039",
      "internal": "Q039",
      "model": "Ranger",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "JTC",
      "sector": "9 DE JULIO",
      "area": "TCT",
      "responsible": "Responsable 6",
      "telepass": "SI",
      "vtv": "2026-10-22",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 73888,
      "driver": "",
      "lastReport": "",
      "x": 33,
      "y": 26
    },
    {
      "id": "V040",
      "domain": "DEM040",
      "internal": "Q040",
      "model": "Berlingo",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "Laliance",
      "sector": "9 DE JULIO",
      "area": "CONTRALOR",
      "responsible": "Responsable 2",
      "telepass": "NO",
      "vtv": "2026-11-21",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 65970,
      "driver": "",
      "lastReport": "",
      "x": 57,
      "y": 71
    },
    {
      "id": "V041",
      "domain": "DEM041",
      "internal": "Q041",
      "model": "Fiorino",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "EDESUR",
      "sector": "PRIMERA JUNTA",
      "area": "CONTRALOR",
      "responsible": "Responsable 7",
      "telepass": "SI",
      "vtv": "2026-10-26",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 150779,
      "driver": "",
      "lastReport": "",
      "x": 67,
      "y": 14
    },
    {
      "id": "V042",
      "domain": "DEM042",
      "internal": "Q042",
      "model": "Amarok",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "OLCA",
      "sector": "12 DE OCT",
      "area": "TCT",
      "responsible": "Responsable 6",
      "telepass": "NO",
      "vtv": "2026-12-27",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 147324,
      "driver": "",
      "lastReport": "",
      "x": 62,
      "y": 78
    },
    {
      "id": "V043",
      "domain": "DEM043",
      "internal": "Q043",
      "model": "Hilux",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "CONTRALOR",
      "responsible": "Responsable 4",
      "telepass": "",
      "vtv": "2026-11-25",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 142034,
      "driver": "",
      "lastReport": "",
      "x": 88,
      "y": 38
    },
    {
      "id": "V044",
      "domain": "DEM044",
      "internal": "Q044",
      "model": "Partner",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 6",
      "telepass": "NO",
      "vtv": "2026-12-03",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 54539,
      "driver": "",
      "lastReport": "",
      "x": 37,
      "y": 57
    },
    {
      "id": "V045",
      "domain": "DEM045",
      "internal": "Q045",
      "model": "Ranger",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "EDESUR",
      "sector": "12 DE OCT",
      "area": "GUARDA",
      "responsible": "Responsable 6",
      "telepass": "",
      "vtv": "2026-11-14",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 69220,
      "driver": "",
      "lastReport": "",
      "x": 61,
      "y": 57
    },
    {
      "id": "V046",
      "domain": "DEM046",
      "internal": "Q046",
      "model": "Berlingo",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2024",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 5",
      "telepass": "NO",
      "vtv": "2026-11-18",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 158165,
      "driver": "",
      "lastReport": "",
      "x": 85,
      "y": 36
    },
    {
      "id": "V047",
      "domain": "DEM047",
      "internal": "Q047",
      "model": "Hilux",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOQ",
      "responsible": "Responsable 7",
      "telepass": "NO",
      "vtv": "2026-12-22",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 58265,
      "driver": "",
      "lastReport": "",
      "x": 67,
      "y": 24
    },
    {
      "id": "V048",
      "domain": "DEM048",
      "internal": "Q048",
      "model": "Berlingo",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2018",
      "company": "EDESUR",
      "sector": "9 DE JULIO",
      "area": "GUARDA",
      "responsible": "Responsable 3",
      "telepass": "NO",
      "vtv": "2026-10-02",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "idle",
      "odometer": 114379,
      "driver": "",
      "lastReport": "",
      "x": 49,
      "y": 35
    },
    {
      "id": "V049",
      "domain": "DEM049",
      "internal": "Q049",
      "model": "Hilux",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2023",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "CONTRALOR",
      "responsible": "Responsable 7",
      "telepass": "NO",
      "vtv": "2026-10-16",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 156405,
      "driver": "",
      "lastReport": "",
      "x": 14,
      "y": 52
    },
    {
      "id": "V050",
      "domain": "DEM050",
      "internal": "Q050",
      "model": "Amarok",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2019",
      "company": "EDESUR",
      "sector": "PRIMERA JUNTA",
      "area": "MEDIDORES",
      "responsible": "Responsable 4",
      "telepass": "SI",
      "vtv": "2026-12-05",
      "vth": "",
      "weight": "",
      "fleetType": "Liviana",
      "status": "available",
      "odometer": 48088,
      "driver": "",
      "lastReport": "",
      "x": 68,
      "y": 22
    },
    {
      "id": "V051",
      "domain": "DEM051",
      "internal": "Q051",
      "model": "Amarok",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2022",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "GRTC",
      "responsible": "Responsable 2",
      "telepass": "SI",
      "vtv": "2026-11-04",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 21731,
      "driver": "",
      "lastReport": "",
      "x": 47,
      "y": 81
    },
    {
      "id": "V052",
      "domain": "DEM052",
      "internal": "Q052",
      "model": "Fiorino",
      "type": "4X2",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "EDESUR",
      "sector": "9 DE JULIO",
      "area": "TCT",
      "responsible": "Responsable 4",
      "telepass": "SI",
      "vtv": "2026-12-25",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 46733,
      "driver": "",
      "lastReport": "",
      "x": 80,
      "y": 13
    },
    {
      "id": "V053",
      "domain": "DEM053",
      "internal": "Q053",
      "model": "Transit",
      "type": "HIDROELEVADOR",
      "equipment": "Equipamiento operativo demo",
      "year": "2024",
      "company": "JTC",
      "sector": "PRIMERA JUNTA",
      "area": "GRTC",
      "responsible": "Responsable 6",
      "telepass": "SI",
      "vtv": "2026-11-27",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 42666,
      "driver": "",
      "lastReport": "",
      "x": 63,
      "y": 54
    },
    {
      "id": "V054",
      "domain": "DEM054",
      "internal": "Q054",
      "model": "Hilux",
      "type": "AUTOMOVIL",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "TCT",
      "responsible": "Responsable 5",
      "telepass": "",
      "vtv": "2026-12-25",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 136863,
      "driver": "",
      "lastReport": "",
      "x": 63,
      "y": 83
    },
    {
      "id": "V055",
      "domain": "DEM055",
      "internal": "Q055",
      "model": "Partner",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "EDESUR",
      "sector": "12 DE OCT",
      "area": "GUARDA",
      "responsible": "Responsable 4",
      "telepass": "NO",
      "vtv": "2026-12-20",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 114349,
      "driver": "",
      "lastReport": "",
      "x": 51,
      "y": 11
    },
    {
      "id": "V056",
      "domain": "DEM056",
      "internal": "Q056",
      "model": "Hilux",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2020",
      "company": "Laliance",
      "sector": "PRIMERA JUNTA",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 5",
      "telepass": "NO",
      "vtv": "2026-11-20",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 87422,
      "driver": "",
      "lastReport": "",
      "x": 79,
      "y": 9
    },
    {
      "id": "V057",
      "domain": "DEM057",
      "internal": "Q057",
      "model": "Amarok",
      "type": "UTILITARIO",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "Laliance",
      "sector": "12 DE OCT",
      "area": "GRTC",
      "responsible": "Responsable 4",
      "telepass": "",
      "vtv": "2026-11-21",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 143665,
      "driver": "",
      "lastReport": "",
      "x": 65,
      "y": 10
    },
    {
      "id": "V058",
      "domain": "DEM058",
      "internal": "Q058",
      "model": "Sprinter",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2021",
      "company": "Laliance",
      "sector": "9 DE JULIO",
      "area": "MEDIDORES",
      "responsible": "Responsable 5",
      "telepass": "",
      "vtv": "2026-12-12",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 154177,
      "driver": "",
      "lastReport": "",
      "x": 52,
      "y": 62
    },
    {
      "id": "V059",
      "domain": "DEM059",
      "internal": "Q059",
      "model": "Transit",
      "type": "4X4",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "JTC",
      "sector": "12 DE OCT",
      "area": "MANTENIMIENTO UOA",
      "responsible": "Responsable 4",
      "telepass": "SI",
      "vtv": "2026-12-07",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "idle",
      "odometer": 46340,
      "driver": "",
      "lastReport": "",
      "x": 76,
      "y": 31
    },
    {
      "id": "V060",
      "domain": "DEM060",
      "internal": "Q060",
      "model": "Amarok",
      "type": "FURGON",
      "equipment": "Equipamiento operativo demo",
      "year": "2025",
      "company": "JTC",
      "sector": "9 DE JULIO",
      "area": "GRTC",
      "responsible": "Responsable 5",
      "telepass": "SI",
      "vtv": "2026-10-10",
      "vth": "",
      "weight": "",
      "fleetType": "Pesada",
      "status": "available",
      "odometer": 109602,
      "driver": "",
      "lastReport": "",
      "x": 30,
      "y": 46
    }
  ],
  "people": [
    {
      "employeeId": "7000001",
      "name": "Conductor Demo 1",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000002",
      "name": "Conductor Demo 2",
      "area": "GRTC",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000003",
      "name": "Conductor Demo 3",
      "area": "MANTENIMIENTO UOA",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000004",
      "name": "Conductor Demo 4",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000005",
      "name": "Conductor Demo 5",
      "area": "MANTENIMIENTO UOA",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000006",
      "name": "Conductor Demo 6",
      "area": "MEDIDORES",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000007",
      "name": "Conductor Demo 7",
      "area": "CONTRALOR",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000008",
      "name": "Conductor Demo 8",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000009",
      "name": "Conductor Demo 9",
      "area": "GRTC",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000010",
      "name": "Conductor Demo 10",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000011",
      "name": "Conductor Demo 11",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000012",
      "name": "Conductor Demo 12",
      "area": "MEDIDORES",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000013",
      "name": "Conductor Demo 13",
      "area": "MANTENIMIENTO UOA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000014",
      "name": "Conductor Demo 14",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000015",
      "name": "Conductor Demo 15",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000016",
      "name": "Conductor Demo 16",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000017",
      "name": "Conductor Demo 17",
      "area": "TCT",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000018",
      "name": "Conductor Demo 18",
      "area": "MANTENIMIENTO UOQ",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000019",
      "name": "Conductor Demo 19",
      "area": "MEDIDORES",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000020",
      "name": "Conductor Demo 20",
      "area": "MANTENIMIENTO UOA",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000021",
      "name": "Conductor Demo 21",
      "area": "MEDIDORES",
      "role": "Conductor operativo",
      "building": "PRIMERA JUNTA",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000022",
      "name": "Conductor Demo 22",
      "area": "GRTC",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000023",
      "name": "Conductor Demo 23",
      "area": "GRTC",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000024",
      "name": "Conductor Demo 24",
      "area": "CONTRALOR",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000025",
      "name": "Conductor Demo 25",
      "area": "MEDIDORES",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000026",
      "name": "Conductor Demo 26",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000027",
      "name": "Conductor Demo 27",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000028",
      "name": "Conductor Demo 28",
      "area": "CONTRALOR",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000029",
      "name": "Conductor Demo 29",
      "area": "GUARDA",
      "role": "Conductor operativo",
      "building": "12 DE OCT",
      "card": "SI",
      "password": "1234"
    },
    {
      "employeeId": "7000030",
      "name": "Conductor Demo 30",
      "area": "GRTC",
      "role": "Conductor operativo",
      "building": "9 DE JULIO",
      "card": "SI",
      "password": "1234"
    }
  ],
  "handovers": [
    {
      "id": "HDEMO001",
      "vehicleId": "V001",
      "domain": "DEM001",
      "employeeId": "7000001",
      "driver": "Conductor Demo 1",
      "odometerStart": 125604,
      "location": "MEDIDORES",
      "checks": {
        "Luces": "ok",
        "Frenos": "ok",
        "Ruedas": "ok",
        "Chapa": "ok",
        "Interior": "ok",
        "Documentacion": "ok",
        "Matafuego": "ok",
        "Herramientas": "ok"
      },
      "result": "ok",
      "notes": "Dato demo para validar el circuito.",
      "createdAt": "2026-10-01T08:30:00.000Z",
      "closedAt": null
    },
    {
      "id": "HDEMO002",
      "vehicleId": "V002",
      "domain": "DEM002",
      "employeeId": "7000002",
      "driver": "Conductor Demo 2",
      "odometerStart": 124974,
      "location": "MANTENIMIENTO UOQ",
      "checks": {
        "Luces": "ok",
        "Frenos": "ok",
        "Ruedas": "warn",
        "Chapa": "ok",
        "Interior": "ok",
        "Documentacion": "ok",
        "Matafuego": "ok",
        "Herramientas": "ok"
      },
      "result": "warn",
      "notes": "Observacion demo preexistente.",
      "createdAt": "2026-10-02T08:30:00.000Z",
      "closedAt": null
    },
    {
      "id": "HDEMO003",
      "vehicleId": "V003",
      "domain": "DEM003",
      "employeeId": "7000003",
      "driver": "Conductor Demo 3",
      "odometerStart": 114595,
      "location": "MANTENIMIENTO UOA",
      "checks": {
        "Luces": "ok",
        "Frenos": "ok",
        "Ruedas": "ok",
        "Chapa": "ok",
        "Interior": "ok",
        "Documentacion": "ok",
        "Matafuego": "ok",
        "Herramientas": "ok"
      },
      "result": "ok",
      "notes": "Dato demo para validar el circuito.",
      "createdAt": "2026-10-03T08:30:00.000Z",
      "closedAt": null
    }
  ]
};
